//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eStoreAdminDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public Currency()
        {
            this.ShipToCountries = new HashSet<ShipToCountry>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public double ExchangeRate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual ICollection<ShipToCountry> ShipToCountries { get; set; }
    }
}
