//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eStoreAdminDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAddress
    {
        public int ID { get; set; }
        public System.Guid UserID { get; set; }
        public int AddressType { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string SuburbCity { get; set; }
        public string StateProvinceRegion { get; set; }
        public string ZipPostcode { get; set; }
        public int CountryID { get; set; }
    
        public virtual ShipToCountry ShipToCountry { get; set; }
        public virtual User User { get; set; }
    }
}
