//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eStoreAdminDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Categories = new HashSet<Category>();
            this.SocialNetworkings = new HashSet<SocialNetworking>();
            this.Products = new HashSet<Product>();
            this.WishLists = new HashSet<WishList>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ImageID { get; set; }
        public string SEOTitle { get; set; }
        public string SEOKeywords { get; set; }
        public string SEODescription { get; set; }
        public string SEOFriendlyNameURL { get; set; }
        public Nullable<bool> C301Redirect { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<SocialNetworking> SocialNetworkings { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<WishList> WishLists { get; set; }
    }
}
