//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eStoreAdminDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ID { get; set; }
        public string EmailAddress { get; set; }
        public string BillingFirstName { get; set; }
        public string BillingLastName { get; set; }
        public string BillingAddress { get; set; }
        public string BillingSuburbCity { get; set; }
        public string BillingStateProvinceRegion { get; set; }
        public string BillingZipPostcode { get; set; }
        public int BillingCountryID { get; set; }
        public string ShippingFirstName { get; set; }
        public string ShippingLastName { get; set; }
        public string ShippingAddress { get; set; }
        public string ShippingSuburbCity { get; set; }
        public string ShippingStateProvinceRegion { get; set; }
        public string ShippingZipPostcode { get; set; }
        public int ShippingCountryID { get; set; }
        public int ShippingModeID { get; set; }
        public double ShippingCost { get; set; }
        public Nullable<int> CCApprovalStatus { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string Comments { get; set; }
        public string GiftTag { get; set; }
        public string TxnID { get; set; }
        public Nullable<System.DateTime> SettlementDate { get; set; }
        public string IsRefunded { get; set; }
        public string RefundPONum { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public Nullable<double> OrderTotal { get; set; }
        public string PayPal_Ack { get; set; }
        public string PayPal_CorrelationID { get; set; }
        public Nullable<System.DateTime> PayPal_TimeStamp { get; set; }
        public Nullable<double> PayPal_FeeAmount { get; set; }
        public string PayPal_PaymentStatus { get; set; }
        public string PayPal_ReasonCode { get; set; }
        public Nullable<System.DateTime> PayPal_PaymentDate { get; set; }
        public Nullable<double> PayPal_NetOfFee { get; set; }
        public string PayPal_RefundTransactionID { get; set; }
        public Nullable<double> PayPal_FeeRefundAmount { get; set; }
        public Nullable<double> PayPal_GrossRefundAmount { get; set; }
        public Nullable<double> PayPal_NetRefundAmount { get; set; }
        public Nullable<double> PayPal_TotalRefundedAmount { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
    
        public virtual ShipToCountry ShipToCountry { get; set; }
        public virtual ShipToMode ShipToMode { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
