//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eStoreAdminDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductColors = new HashSet<ProductColor>();
            this.ProductImages = new HashSet<ProductImage>();
            this.ProductSizes = new HashSet<ProductSize>();
            this.SocialNetworkings = new HashSet<SocialNetworking>();
            this.WishLists = new HashSet<WishList>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int SupplierID { get; set; }
        public Nullable<int> CatID { get; set; }
        public Nullable<int> DepID { get; set; }
        public int QuantityPerUnit { get; set; }
        public decimal UnitPrice { get; set; }
        public double Weight { get; set; }
        public int UnitsInStock { get; set; }
        public int UnitsOnOrder { get; set; }
        public int ReOrderLevel { get; set; }
        public int Active { get; set; }
        public int IsOnSale { get; set; }
        public Nullable<decimal> DiscountUnitPrice { get; set; }
        public int NumViews { get; set; }
        public decimal WholesalePrice { get; set; }
        public string SEOTitle { get; set; }
        public string SEOKeywords { get; set; }
        public string SEODescription { get; set; }
        public string SEOFriendlyNameURL { get; set; }
        public bool C301Redirect { get; set; }
        public int BrandID { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<ProductColor> ProductColors { get; set; }
        public virtual ICollection<ProductImage> ProductImages { get; set; }
        public virtual ICollection<ProductSize> ProductSizes { get; set; }
        public virtual ICollection<SocialNetworking> SocialNetworkings { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<WishList> WishLists { get; set; }
    }
}
