//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eStoreAdminDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipCost
    {
        public int ID { get; set; }
        public int ZoneID { get; set; }
        public int ModeID { get; set; }
        public double MaxWeight { get; set; }
        public double Price { get; set; }
    
        public virtual Zone Zone { get; set; }
        public virtual ShipToMode ShipToMode { get; set; }
    }
}
