//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eStoreAdminDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipToCountry
    {
        public ShipToCountry()
        {
            this.CustomerAddresses = new HashSet<CustomerAddress>();
            this.Orders = new HashSet<Order>();
        }
    
        public int ID { get; set; }
        public int CurrencyID { get; set; }
        public int ZoneID { get; set; }
        public string Name { get; set; }
        public string CountryCode { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual ICollection<CustomerAddress> CustomerAddresses { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Zone Zone { get; set; }
    }
}
