//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eStoreAdminDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishList
    {
        public int ID { get; set; }
        public System.Guid UserID { get; set; }
        public int DepID { get; set; }
        public int CatID { get; set; }
        public int ProdID { get; set; }
        public string ProdDetails { get; set; }
        public string ImgPath { get; set; }
        public decimal UnitPrice { get; set; }
        public double ProdWeight { get; set; }
        public int Quantity { get; set; }
        public int IsOnSale { get; set; }
        public decimal DiscPrice { get; set; }
        public int ColorID { get; set; }
        public string ColorName { get; set; }
        public int SizeID { get; set; }
        public string SizeName { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Department Department { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
