//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace eStoreAdminWeb.Controls {
    
    
    public partial class MasterMenu {
        
        /// <summary>
        /// ManagerTopMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::eStoreAdminWeb.Controls.ManagerMenu ManagerTopMenu;
        
        /// <summary>
        /// AdminTopMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::eStoreAdminWeb.Controls.AdminMenu AdminTopMenu;
        
        /// <summary>
        /// StaffTopMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::eStoreAdminWeb.Controls.StaffMenu StaffTopMenu;
    }
}
