<%@ Page Language="C#" MasterPageFile="~/MasterPages/eStoreAdminMaster.Master" AutoEventWireup="true" CodeBehind="ChangeMyPassword.aspx.cs" Inherits="eStoreAdminWeb.Authentication.ChangeMyPassword" %>
<asp:Content ID="MainContent" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <h1>Change Password</h1>
    <asp:ChangePassword ID="ChangeThePassword" runat="server"
                        BackColor="#F7F6F3" 
                        BorderColor="#E6E2D8" 
                        BorderPadding="4" 
                        BorderStyle="Solid" 
                        BorderWidth="1px" 
                        Font-Names="Verdana" 
                        ForeColor="#333333"
                        TitleTextStyle-Font-Size="Medium"
                        TitleTextStyle-BackColor="#5D7B9D"
                        TitleTextStyle-Font-Bold="True" 
                        TitleTextStyle-ForeColor="White"
                        InstructionTextStyle-Font-Italic="true"
                        InstructionTextStyle-ForeColor="Black"
                        FailureTextStyle-Font-Bold="true"
                        FailureTextStyle-ForeColor="Red"
                        CancelButtonStyle-BackColor="#FFFBFF" 
                        CancelButtonStyle-BorderColor="#CCCCCC"
                        CancelButtonStyle-BorderStyle="Solid"
                        CancelButtonStyle-BorderWidth="1px"
                        CancelButtonStyle-Font-Names="Verdana"
                        CancelButtonStyle-ForeColor="#284775"
                        ContinueButtonStyle-BackColor="#FFFBFF" 
                        ContinueButtonStyle-BorderColor="#CCCCCC"
                        ContinueButtonStyle-BorderStyle="Solid"
                        ContinueButtonStyle-BorderWidth="1px"
                        ContinueButtonStyle-Font-Names="Verdana"
                        ContinueButtonStyle-ForeColor="#284775"
                        ChangePasswordButtonStyle-BackColor="#FFFBFF" 
                        ChangePasswordButtonStyle-BorderColor="#CCCCCC"
                        ChangePasswordButtonStyle-BorderStyle="Solid"
                        ChangePasswordButtonStyle-BorderWidth="1px"
                        ChangePasswordButtonStyle-Font-Names="Verdana"
                        ChangePasswordButtonStyle-ForeColor="#284775"
                        PasswordHintStyle-Font-Italic="true"
                        PasswordHintStyle-ForeColor="#284775"
                        CancelDestinationPageUrl="GoToHomePage.aspx"
                        ContinueDestinationPageUrl="GoToHomePage.aspx"
                        OnChangedPassword="ChangeThePassword_PasswordChanged"
                        OnChangePasswordError="ChangeThePassword_PasswordChangeError"
                        OnSendMailError="ChangeThePassword_SendMailError" />
    </asp:Content>