<%@ Page Title="Administration - Forgotten Password" Language="C#" MasterPageFile="~/MasterPages/eStoreAdminLoginMaster.Master" AutoEventWireup="true" CodeBehind="ForgottenPassword.aspx.cs" Inherits="eStoreAdminWeb.Authentication.ForgottenPassword" %>
<%@ Import Namespace="eStoreAdminWeb" %>
<asp:Content ID="MainContent" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <h1>Forgotten Password</h1>
    <asp:PasswordRecovery ID="PasswordRecovery1" runat="server" 
                          BackColor="#F7F6F3" 
                          BorderColor="#E6E2D8" 
                          BorderPadding="4" 
                          BorderStyle="Solid" 
                          BorderWidth="1px" 
                          Font-Names="Verdana" 
                          Font-Size="Small"
                          ForeColor="#333333"
                          TitleTextStyle-Font-Size="Medium"
                          TitleTextStyle-BackColor="#5D7B9D"
                          TitleTextStyle-Font-Bold="True" 
                          TitleTextStyle-ForeColor="White"
                          InstructionTextStyle-Font-Italic="true"
                          InstructionTextStyle-ForeColor="Black"
                          FailureTextStyle-Font-Bold="true"
                          FailureTextStyle-ForeColor="Red"
                          SubmitButtonStyle-BackColor="#FFFBFF" 
                          SubmitButtonStyle-BorderColor="#CCCCCC"
                          SubmitButtonStyle-BorderStyle="Solid"
                          SubmitButtonStyle-BorderWidth="1px"
                          SubmitButtonStyle-Font-Names="Verdana"
                          SubmitButtonStyle-ForeColor="#284775"
                          SubmitButtonStyle-Font-Size="Small"
                          SuccessTextStyle-ForeColor="#507CD1"
                          SuccessTextStyle-Font-Bold="true"
                          MailDefinition-From="phoenixconsulting@gmail.com"
                          MailDefinition-IsBodyHtml="false"
                          MailDefinition-Priority="Normal"
                          MailDefinition-Subject="Password Reset"
                          OnAnswerLookupError="PasswordRecovery1_AnswerLookupError"
                          OnSendMailError="PasswordRecovery1_SendMailError"
                          OnUserLookupError="PasswordRecovery1_UserLookupError"
                          OnSendingMail="PasswordRecovery1_SendingMail" />
</asp:Content>
